### ISSUE TITLE
Recommend to return the promises from your thunks

### ISSUE THREAD

**Issue by ctrlplusb** [gizemocak/OMDB-auto-complete#1]
Hey @gizemocak 👋

Great project. 👍

Just a small note - it's best practice to return the promises from your thunks. This will ensure that Easy Peasy can track when the thunk has completed. This helps with the dev tools output, and advanced features such as listeners.

e.g.

```javascript
  fetchSelectedMovie: thunk(async (actions, id) => {
    actions.updateLoading(true);
    // 👇 return me
    return fetch(`http://www.omdbapi.com/?apikey=bce872a9&i=${id}`)
      .then(res => res.json())
      .then(res => {
        actions.updateSelectedMovie(res);
        actions.updateLoading(false);
      });
  }),
```

**Comment by gizemocak** [comment]
Hi Sean,

Thanks a lot for the feedback!
I will make sure implement that change.

Gizem
________________________________

**Comment by ctrlplusb** [comment]
🙏
